name: Descompactar ZIP existente

on:
  workflow_dispatch: # permite rodar manualmente pela aba "Actions"

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Descompactar ZIP
        run: |
          mkdir -p descompactado
          unzip -o AndroidFrameGenv1.zip -d descompactado

      - name: Commitar arquivos descompactados
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cp -r descompactado/* .
          git add .
          git commit -m "Descompactado meu-pacote.zip automaticamente"
          git push
