name: Build APK com NDK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Compilar APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Instalar Android SDK + NDK
        uses: android-actions/setup-android@v2
        with:
          ndk: true
          cmake: true

      - name: Permitir execução do gradlew
        run: chmod +x ./gradlew

      - name: Build do APK Debug
        run: ./gradlew assembleDebug

      - name: Upload do APK
        uses: actions/upload-artifact@v2
        with:
          name: meu-apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk
